In [41]:
import pandas as pd

df = pd.read_excel("data_spk.xlsx")
df

,Tanggal,Nomor SPK,Area / Mesin,Mulai Pengerjaan,Selesai Pengerjaan,Jenis Kerusakan,Penyelesaian,Keterangan/Penyebab,Masuk Bengkel,Keluar Bengkel
0,2025-03-11 00:00:00,119608,FK 53,NaN,NaN,1. Cek rutin,Belum update/ Proses,NaN,NaN,NaN
1,2025-03-11 00:00:00,119609,FK 16,NaN,NaN,"1. Cek rutin, 2. Seal stick rembes, 3. Lift tu...",Belum update/ Proses,NaN,NaN,NaN
2,2025-03-11 00:00:00,117148,FK 50,NaN,NaN,1. Vanbelt alternator putus,Belum update/ Proses,Booking,NaN,NaN
3,2025-03-11 00:00:00,119604,FK 40 (34436),NaN,NaN,"1. Cek rutin, 2. Pir pedal kopling putus, 3. B...",Belum update/ Proses,NaN,NaN,NaN
4,2025-03-11 00:00:00,119607,FK 43,NaN,NaN,"1. Cek rutin, 2. Control valve rembes, 3. Lamp...",Belum update/ Proses,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
234,2025-03-19,119631,FK 16 (40295),NaN,NaN,"1. Cek rutin, 2. Lift turun sendiri, 3. Baut r...",NaN,NaN,NaN,NaN
235,2025-03-19,119633,FK 28 (40777),NaN,NaN,1. Dinamo starter trouble,NaN,NaN,NaN,NaN
236,2025-03-19,119635,FK 53 (860),NaN,NaN,"1. Cek rutin, 2. Tampilan pos board tidak normal",NaN,NaN,NaN,NaN
237,2025-03-19,119634,FK 52 (9332),NaN,NaN,1. Ban depan sisi kiri tergerus velg,NaN,NaN,NaN,NaN
238,2025-03-20,119639,FK 23 (42919),NaN,NaN,"1. Klakson trouble, 2. Rem blong, 3. Panel sol...",NaN,NaN,NaN,NaN

In [28]:
df["Masuk Bengkel"][230]

datetime.time(8, 25)

In [29]:
from datetime import time
import pandas as pd
import numpy as np

def convert_to_time(value):
    if pd.isna(value) or value == '' or value is None:
        return None
    try:
        str_val = str(value).strip()
        if '.' in str_val:
            jam, menit = str_val.split('.')
            jam = int(jam)
            menit = int(menit.ljust(2, '0')[:2])
        else:
            jam = int(str_val)
            menit = 0
        return time(jam, menit)
    except:
        return None

# Terapkan ke kolom
df["Mulai Pengerjaan"] = df["Mulai Pengerjaan"].apply(convert_to_time)
df["Selesai Pengerjaan"] = df["Selesai Pengerjaan"].apply(convert_to_time)

# Tampilkan hasil
df

,Tanggal,Nomor SPK,Area / Mesin,Mulai Pengerjaan,Selesai Pengerjaan,Jenis Kerusakan,Penyelesaian,Keterangan/Penyebab,Tanggal Pengerjaan,Masuk Bengkel,Keluar Bengkel
0,2024-06-13,119608,FK 53,None,None,1. Cek rutin,Belum update/ Proses,NaN,NaT,NaN,NaN
1,2024-06-13,119609,FK 16,None,None,"1. Cek rutin, 2. Seal stick rembes, 3. Lift tu...",Belum update/ Proses,NaN,NaT,NaN,NaN
2,2024-06-13,117148,FK 50,None,None,1. Vanbelt alternator putus,Belum update/ Proses,Booking,NaT,NaN,NaN
3,2024-06-13,119604,FK 40 (34436),None,None,"1. Cek rutin, 2. Pir pedal kopling putus, 3. B...",Belum update/ Proses,NaN,NaT,NaN,NaN
4,2024-06-13,119607,FK 43,None,None,"1. Cek rutin, 2. Control valve rembes, 3. Lamp...",Belum update/ Proses,NaN,NaT,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
228,NaT,119624,FK 17 (42726),None,None,"1. Cek rutin, 2. Kampas kopling suaranya kasar...",Belum update/ Proses,NaN,NaT,NaN,NaN
229,NaT,119625,FK 19,None,None,"1. Cek rutin, 2. Lampu utama padam, 3. Bearing...",Belum update/ Proses,NaN,NaT,NaN,NaN
230,NaT,119651,FK 50 (9899),None,None,"1. Cek rutin, 2. Bearing lift aus, 3. Ban peca...",Belum update/ Proses,NaN,NaT,08:25:00,NaN
231,NaT,119652,FK 21 (42262),None,None,"1. Cek rutin, 2. Suara transmisi kasar, 3. Pom...",Belum update/ Proses,NaN,NaT,NaN,NaN
232,NaT,119630,FK 27,None,None,"1. Cek rutin, 2. Rantai putus, 3. Baut roda pu...",Belum update/ Proses,NaN,NaT,NaN,NaN

In [30]:
df["Mulai Pengerjaan"][23]

datetime.time(8, 30)

In [31]:
df.loc[23]

Tanggal                                              2024-05-31 00:00:00
Nomor SPK                                                         117116
Area / Mesin                                                       FK 21
Mulai Pengerjaan                                                08:30:00
Selesai Pengerjaan                                              10:00:00
Jenis Kerusakan        1. Cek rutin, 2. Knalpot kocak, 3. Pompa hidro...
Penyelesaian           1. Cleaning fk dan filter udara, 2. Grease nep...
Keterangan/Penyebab                                                  NaN
Tanggal Pengerjaan                                                   NaT
Masuk Bengkel                                                        NaN
Keluar Bengkel                                                       NaN
Name: 23, dtype: object

In [60]:
df.to_excel("data_spk.xlsx", index=False)

In [47]:
def hitung_kerusakan(teks):
    if not teks or teks == "":
        return 0
    if pd.isna(teks) or teks == '' or teks is None:
        return 0
    
    # Hitung jumlah item berdasarkan koma
    jumlah_kerusakan = teks.count(',') + 1

    # Jika mengandung "cek rutin", kurangi 1
    if 'cek rutin' in teks.lower():
        jumlah_kerusakan -= 1

    return jumlah_kerusakan

In [48]:
df['Total Kerusakan'] = df["Jenis Kerusakan"].apply(hitung_kerusakan)

1

In [58]:
for i in range(10):
    print(f"Total Kerusakan :{df["Total Kerusakan"][i]}")
    print(df["Jenis Kerusakan"][i],"\n")

Total Kerusakan :0
1. Cek rutin

Total Kerusakan :5
1. Cek rutin, 2. Seal stick rembes, 3. Lift turun sendiri, 4. Lampu utama padam, 5. Cek kelistrikan, 6. Seal kopling atas rembes

Total Kerusakan :1
1. Vanbelt alternator putus

Total Kerusakan :5
1. Cek rutin, 2. Pir pedal kopling putus, 3. Bearing lift rusak 1, 4. Lampu utama padam, 5. Cek terot, 6. Cek kelistrikan

Total Kerusakan :3
1. Cek rutin, 2. Control valve rembes, 3. Lampu utama kanan padam, 4. Pin terot kiri aus

Total Kerusakan :1
1. Bearing lift protol

Total Kerusakan :4
1. Cek rutin, 2. Lift turun sendiri, 3. Cylinder steering rembes, 4. Selang hidrolik area kontrol valve rembes, 5. Kelistrikan

Total Kerusakan :5
1. Cek rutin, 2. Mesin ngobos/suara kasar, 3. Cylinder steering rembes, 4. Perseneling susah dimasukkan, 5. Seal stick transmisi rembes, 6. Lift turun sendiri

Total Kerusakan :4
1. Cek rutin, 2. Ban depan pecah-pecah, 3. Stir liar, 4. Kontrol valve rembes, 5. Seal rem atas rembes

Total Kerusakan :4
40x40 = 150 pcs, 30x30 = 50 pcs, 50x50 = 100 pcs, 60x60 = 100 pcs

In [19]:
import pandas as pd
import numpy as np

# Contoh pembacaan data dari file Excel (sesuaikan dengan sumber data yang digunakan)
df = pd.read_excel("HM_Harian.xlsx")

# Mengubah kolom kecuali 'Tanggal' menjadi numerik jika memungkinkan, jika tidak biarkan dalam bentuk aslinya
def convert_to_numeric(value):
    try:
        return float(value)
    except ValueError:
        return value  # Jika bukan angka, biarkan tetap dalam bentuk aslinya

df.iloc[:, 1:] = df.iloc[:, 1:].applymap(convert_to_numeric)

# Menghitung penggunaan forklift tiap shift dengan mempertahankan nilai non-numerik
usage_df = df.copy()

num_forklifts = 26  # Total forklift
shifts_per_forklift = 3  # Shift per forklift
total_columns = num_forklifts * shifts_per_forklift

cols = df.columns[1:total_columns + 1]  # Semua kolom kecuali 'Tanggal'

for i in range(num_forklifts):  # Loop per forklift
    shift_1_idx = i * shifts_per_forklift
    shift_2_idx = shift_1_idx + 1
    shift_3_idx = shift_1_idx + 2
    
    shift_1_col = cols[shift_1_idx]
    shift_2_col = cols[shift_2_idx]
    shift_3_col = cols[shift_3_idx]
    
    # Shift 1 = Shift 2 - Shift 1 (jika keduanya angka, jika tidak salin saja)
    usage_df[shift_1_col] = df.apply(lambda row: row[shift_2_col] - row[shift_1_col] 
                                     if isinstance(row[shift_2_col], (int, float)) and isinstance(row[shift_1_col], (int, float))
                                     else row[shift_1_col], axis=1)
    
    # Shift 2 = Shift 3 - Shift 2
    usage_df[shift_2_col] = df.apply(lambda row: row[shift_3_col] - row[shift_2_col] 
                                     if isinstance(row[shift_3_col], (int, float)) and isinstance(row[shift_2_col], (int, float))
                                     else row[shift_2_col], axis=1)
    
    # Shift 3 = Shift 1 (hari berikutnya) - Shift 3
    usage_df[shift_3_col] = df.apply(lambda row: row[shift_3_col] if isinstance(row[shift_3_col], str) else 
                                     (df[shift_1_col].shift(-1).iloc[row.name] - row[shift_3_col] 
                                      if row.name < len(df) - 1 and isinstance(df[shift_1_col].shift(-1).iloc[row.name], (int, float)) 
                                      and isinstance(row[shift_3_col], (int, float)) else row[shift_3_col]), axis=1)

# Menyimpan hasil ke file baru
usage_df.to_excel("penggunaan_forklift.xlsx", index=False)

print("Perhitungan selesai. Data disimpan di 'penggunaan_forklift.xlsx'")

C:\Users\Pongo\AppData\Local\Temp\ipykernel_10776\2053670587.py:14: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.iloc[:, 1:] = df.iloc[:, 1:].applymap(convert_to_numeric)

Perhitungan selesai. Data disimpan di 'penggunaan_forklift.xlsx'

In [2]:
import pandas as pd
import numpy as np

# Baca data dari file Excel (sesuaikan nama file jika perlu)
df = pd.read_excel("HM_Harian.xlsx")

# Fungsi untuk mencoba mengonversi ke float, jika tidak berhasil maka biarkan nilai aslinya
def convert_to_numeric(value):
    try:
        return float(value)
    except (ValueError, TypeError):
        return value

# Ubah semua kolom kecuali 'Tanggal'
df.iloc[:, 1:] = df.iloc[:, 1:].applymap(convert_to_numeric)

# DataFrame untuk hasil penggunaan
usage_df = df.copy()

num_forklifts = 26       # Total forklift
shifts_per_forklift = 3  # Shift per forklift
total_columns = num_forklifts * shifts_per_forklift

# Kolom-kolom yang akan dihitung (semua kolom kecuali Tanggal)
cols = df.columns[1:total_columns + 1]

# Proses per forklift
for i in range(num_forklifts):
    # Dapatkan daftar kolom untuk forklift ke-i
    forklift_cols = [cols[i * shifts_per_forklift + j] for j in range(shifts_per_forklift)]
    
    # Kumpulkan posisi (baris, kolom) untuk forklift ini secara berurutan
    positions = []
    for r in range(len(df)):
        for col in forklift_cols:
            positions.append((r, col))
    
    # Untuk setiap posisi, jika nilai adalah angka, cari nilai angka berikutnya dalam urutan positions
    for index, (r, col) in enumerate(positions):
        current_val = df.at[r, col]
        if isinstance(current_val, (int, float)):
            # Cari nilai numerik berikutnya di daftar positions
            next_numeric = None
            for j in range(index + 1, len(positions)):
                r_next, col_next = positions[j]
                candidate = df.at[r_next, col_next]
                if isinstance(candidate, (int, float)):
                    next_numeric = candidate
                    break
            # Jika ditemukan, hitung selisihnya
            if next_numeric is not None:
                usage_df.at[r, col] = next_numeric - current_val
            else:
                usage_df.at[r, col] = current_val
        else:
            # Jika bukan angka, salin nilai aslinya
            usage_df.at[r, col] = current_val

# Simpan hasil ke file baru
usage_df.to_excel("penggunaan_forklift.xlsx", index=False)

print("Perhitungan selesai. Data disimpan di 'penggunaan_forklift.xlsx'")

C:\Users\Pongo\AppData\Local\Temp\ipykernel_10684\3215002837.py:15: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.iloc[:, 1:] = df.iloc[:, 1:].applymap(convert_to_numeric)

Perhitungan selesai. Data disimpan di 'penggunaan_forklift.xlsx'

In [4]:
import pandas as pd

# Baca file Excel
df = pd.read_excel('data_spk.xlsx')

# Ubah kolom Tanggal menjadi format datetime, lalu ambil hanya tanggalnya
df['Tanggal'] = pd.to_datetime(df['Tanggal']).dt.date

# Simpan kembali ke Excel (jika diperlukan)
df.to_excel('data_spk.xlsx', index=False)

In [2]:
import streamlit
print(streamlit.__version__)

1.42.2